name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io -sSf | sh

      - name: Build WASM package
        # This generates the ../pkg folder with the .d.ts files
        run: wasm-pack build 

      - name: Install JS dependencies
        run: yarn install

      - name: Run Build
        run: yarn build


